### ISSUE TITLE
Implement Slack App Manifest

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor-app-slack#3]
It seems to we'll be able to make the installation process more user-friendly using Slack App Manifest: https://api.slack.com/reference/manifests#sharing_manifests . 

Requirements:
- [ ] Add app manifest with required webhooks
- [ ] Configuration view at Saleor Dashboard should have a button to connect our App to Slack instead of a manual webhook setup

**Comment by kzuraw** [comment]
I've dug a bit of Slack documentation and I've found out that you can programmatically receive a webhook URL when the user creates an app ([doc reference](https://api.slack.com/messaging/webhooks)).

I'm attaching a screenshot as Slack docs can't link to headers 🤷

![CleanShot 2022-10-11 at 10 09 32@2x](https://user-images.githubusercontent.com/9116238/195034702-9c0bf22d-38cd-4c8b-8583-8b07a39a928d.jpg)

## Proposed flow
```mermaid
sequenceDiagram
    participant app
    participant slack
    app->>slack: share app manifest
    slack->>app: send back webhook URL
    app->>app: saves webhook URL
```

**Comment by kzuraw** [comment]
After further investigation, I found out that implementing the changes proposed by my comment will require migrating to OAuth flow so I will skip this part for now.
