### ISSUE TITLE
Prepare multi-tenancy

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-slack#7]
This app can work in Multi-tenant mode (single deployment, multiple Saleors)

There is preparation for that

At the moment, Upstash can be used as APL (during development)
https://github.com/saleor/saleor-app-sdk/pull/78/files#diff-02b845c068f1355ded14c02223f9762d18e10bdcbbc2cd430e474dbdb6412e4a

Later, will be replaced with Saleor Cloud APL (WIP)

**Comment by kzuraw** [comment]
I'm wondering if we want to use Upstash right now if we do not have production-ready storage?
Or use Upstash and for prod use single-tenant Vercel APL?

**Comment by lkostrowski** [comment]
APL architecture covers this - you must implement any APL and you can replace it to any implementation with literally replacing an argument. 

We are not sure when Cloud APL will be ready, but we can definitely continue working on Slack app and test it locally during this time. Interface is stable
