### ISSUE TITLE
Add richer UI with embeded descrptions

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-app-slack#8]
App, then opened, shouldn't require looking for documentation inside repository. Main app screen in dashboard should have some basic descriptions, maybe branding - in general good look and feel. Inputs should be described. Links to repository and readmes provided inside it

**Comment by kzuraw** [comment]
@lkostrowski Can you check if #5 does not help a bit with this issue?

**Comment by lkostrowski** [comment]
Yea it does, but can you add e.g. link to Slack docs/webhooks there?

**Comment by kzuraw** [comment]
@lkostrowski added - please take a look into #5 😄

**Comment by kzuraw** [comment]
I'm closing this one as changes were implemented in #5
